/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks Endpoint
         * @description Return a paginated, optionally-filtered list of tasks.
         *
         *     Pagination is cursor-based: pass ``cursor=<ISO-datetime>`` from
         *     ``next_cursor`` in the previous page to advance.  ``next_cursor`` is
         *     ``null`` when no further pages exist.
         */
        get: operations["list_tasks_endpoint_api_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count Tasks Endpoint
         * @description Return total task count (supports the same filters as /api/tasks).
         */
        get: operations["count_tasks_endpoint_api_tasks_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Endpoint
         * @description Return the fully-hydrated Task including all push_events.
         */
        get: operations["get_task_endpoint_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Task Endpoint
         * @description Cancel the brokerage order associated with a task.
         *
         *     Returns 404 if the task doesn't exist, 400 if it has no ``order_id``
         *     (not yet submitted), or 502 if the broker call fails.
         */
        post: operations["cancel_task_endpoint_api_tasks__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats Today Endpoint
         * @description Return today's task counts grouped into summary buckets.
         */
        get: operations["stats_today_endpoint_api_stats_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Positions Endpoint
         * @description Return current positions split into stocks and options.
         *
         *     Pulls live from the broker on every call (no DB cache yet) so the
         *     dashboard cards reflect the latest holdings without a periodic sync
         *     job. If the broker is down we fall back to ``[]`` rather than 502 —
         *     the dashboard treats absence as "no positions" and skips quote/
         *     candlestick fetches.
         *
         *     Longbridge's ``stock_positions`` endpoint actually returns BOTH
         *     stocks and option contracts the user holds (the option contracts
         *     carry an OCC-format symbol). We classify each row via
         *     ``parse_option_symbol`` and route to the appropriate bucket.
         */
        get: operations["list_positions_endpoint_api_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pairs Endpoint
         * @description List做T pairs for the active account, optionally filtered by
         *     ticker. Cross-account isolation is enforced via the broker's
         *     ``account_id``; pairs created under a different account stay
         *     hidden after switching.
         *
         *     Paginated: ``offset`` / ``limit`` slice the result. The response
         *     carries ``total_count`` and ``has_more`` so the UI can render a
         *     "已加载 M / N · 加载更多" affordance without a separate count call.
         */
        get: operations["list_pairs_endpoint_api_pairs_get"];
        put?: never;
        /**
         * Create Pair Endpoint
         * @description Create a做T pair binding broker fills (one row per order_id).
         *     Server auto-balances qty using FIFO; leftover qty stays on the
         *     originating fills for future bindings.
         */
        post: operations["create_pair_endpoint_api_pairs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairs/{pair_id}/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extend Pair Endpoint
         * @description Add trades to an existing做T pair.
         */
        post: operations["extend_pair_endpoint_api_pairs__pair_id__extend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairs/{pair_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Pair Endpoint
         * @description Unbind a做T pair. The underlying trades become available again.
         */
        delete: operations["delete_pair_endpoint_api_pairs__pair_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quote Endpoint
         * @description Fetch snapshot quotes for the comma-separated symbol list.
         *
         *     Symbols missing from the broker's response are silently dropped from
         *     the result — callers should expect a possibly-smaller result set.
         */
        get: operations["quote_endpoint_api_quote_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Watch Quotes Endpoint
         * @description Set the symbols whose quote push-stream the backend forwards
         *     to WS clients. Replaces the previous set — backend diffs and
         *     issues subscribe/unsubscribe to the broker.
         *
         *     Frontend calls this once after positions resolve, and again on
         *     every account switch (after /broker/reload). Empty list clears
         *     all subscriptions (used on dashboard unmount / logout).
         *
         *     Returns 503 when no SubscriptionManager is bound yet (early
         *     startup window before broker init completes, or right after an
         *     account-switch reload tore the old manager down) — frontend
         *     retries on the next positions tick.
         */
        post: operations["watch_quotes_endpoint_api_quotes_watch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candlesticks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candlesticks Endpoint
         * @description Return candlestick bars for a single symbol.
         *
         *     For `today`, granularity (2/3/5 min) and sessions (regular vs
         *     pre+post) are user-selectable so the user can choose between a
         *     clean regular-hours curve and a wider view that includes pre-market
         *     and after-hours. For other periods these query params are ignored
         *     (fixed mapping):
         *       5/7 → 5-min, 15 → 15-min, 30/60/90 → daily.
         */
        get: operations["candlesticks_endpoint_api_candlesticks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/broker/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History Executions Endpoint
         * @description Broker-side fill history for the detail pane's trade list.
         *
         *     Incremental sync: starts from MAX(ts) already in DB for this
         *     account (+ optional ticker), pulls only the gap from the broker,
         *     upserts. First-ever open falls back to a 90-day window. Read
         *     comes from DB filtered by account_id so cross-account bleed is
         *     impossible and broker outages still serve cached data.
         *
         *     Paginated: ``offset`` / ``limit`` slice the result newest-first.
         *     Sync runs on every call (idempotent upsert) so a "加载更多" click
         *     also picks up new fills that arrived since the previous page.
         *     Response carries ``total_count`` / ``has_more`` so the UI can
         *     accumulate pages into a single store for cross-page做T binding.
         */
        get: operations["history_executions_endpoint_api_broker_executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/broker/today_executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Today Executions Endpoint
         * @description Today's (ET trading day) order-level executions for the active
         *     account. Same DB-backed path as /api/broker/executions but with a
         *     narrow window — used by Day P/L on position cards.
         *
         *     Sync pulls today_executions from the broker (which already covers
         *     ~30h via history_executions internally) and upserts as one row
         *     per order. Frontend re-filters by ET trading day client-side.
         */
        get: operations["today_executions_endpoint_api_broker_today_executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trades Endpoint
         * @description Return chronologically-ordered FILLED / PARTIAL trades for a ticker.
         *
         *     Each entry corresponds to one task (its id is the trade_id used in
         *     做T pair allocations). Unfilled tasks (no cumulative_qty) are
         *     filtered out — they have no position to bind.
         */
        get: operations["trades_endpoint_api_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Endpoint
         * @description Return service liveness + mode status.
         *
         *     ``whop`` is always ``"down"`` until the Phase 6 Whop scraper is wired
         *     into the health probe.  ``longport`` is assumed ``"up"`` because the
         *     broker is injected at startup (real health-check is future work).
         */
        get: operations["health_endpoint_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/longport/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Longport Settings */
        get: operations["get_longport_settings_api_longport_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Longport Settings */
        patch: operations["patch_longport_settings_api_longport_settings_patch"];
        trace?: never;
    };
    "/api/longport/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Longport Oauth Start
         * @description Start a fresh OAuth flow to add a new LongBridge account slot.
         *
         *     Always registers a brand-new OAuth client_id — there is no concept
         *     of "re-using" a previously-authorized account here, because each
         *     invocation expresses the user's intent to add an account.
         */
        post: operations["post_longport_oauth_start_api_longport_oauth_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/longport/oauth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Longport Oauth Status */
        get: operations["get_longport_oauth_status_api_longport_oauth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/longport/oauth/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Longport Oauth Activate
         * @description Set ``account_id`` as the active account. Caller is expected to
         *     invoke /broker/reload separately to actually swap the broker.
         */
        post: operations["post_longport_oauth_activate_api_longport_oauth_activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/longport/oauth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Longport Oauth Logout
         * @description Remove an account: scrub the SDK token cache, drop from the
         *     settings list. If it was the active account, fall back to whatever
         *     account remains.
         */
        post: operations["post_longport_oauth_logout_api_longport_oauth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/longport/oauth/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Longport Oauth Account
         * @description Rename an account's display label.
         */
        patch: operations["patch_longport_oauth_account_api_longport_oauth_account_patch"];
        trace?: never;
    };
    "/api/longport/broker/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Broker Status */
        get: operations["get_broker_status_api_longport_broker_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/longport/broker/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Broker Reload
         * @description Tear down the current broker + push subscription, build a
         *     new one from the latest credentials in runtime store, and
         *     return the resulting status. Used by the UI's refresh button.
         */
        post: operations["post_broker_reload_api_longport_broker_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Task Endpoint */
        post: operations["confirm_task_endpoint_api_tasks__task_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip Task Endpoint
         * @description Mark an INSTRUCTION_READY task as SKIPPED on user request.
         */
        post: operations["skip_task_endpoint_api_tasks__task_id__skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Whop Pages */
        get: operations["list_whop_pages_api_whop_pages_get"];
        put?: never;
        /** Create Whop Page */
        post: operations["create_whop_page_api_whop_pages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/pages/{page_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Whop Page */
        delete: operations["delete_whop_page_api_whop_pages__page_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/pages/{page_id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart Whop Page */
        post: operations["restart_whop_page_api_whop_pages__page_id__restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/pages/{page_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Whop Page Endpoint
         * @description Start the Playwright listener for a page.
         *
         *     Idempotent w.r.t. the entry: if a listener is already running it
         *     is stopped and re-started (same semantics as restart). Returns 404
         *     if the page id is unknown OR if Playwright launch fails.
         */
        post: operations["start_whop_page_endpoint_api_whop_pages__page_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/pages/{page_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Whop Page Endpoint
         * @description Stop the Playwright listener for a page (entry stays).
         *
         *     Idempotent: returns 200 even if no listener was running. Returns
         *     404 only when the entry id is unknown.
         */
        post: operations["stop_whop_page_endpoint_api_whop_pages__page_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/pages/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whop Settings Defaults */
        get: operations["whop_settings_defaults_api_whop_pages_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/pages/{page_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Whop Page Settings */
        patch: operations["patch_whop_page_settings_api_whop_pages__page_id__settings_patch"];
        trace?: never;
    };
    "/api/whop/orphan/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cleanup Orphan Tasks
         * @description Delete all tasks (and linked rows) for a given url.
         *
         *     Defensive: rejects (400) if the url is currently registered to an
         *     active page — unless `force=true`. The orphan-cleanup UI never
         *     sets force; the per-page settings modal "清空本页历史" sets
         *     force=true since it's an explicit user choice.
         */
        post: operations["cleanup_orphan_tasks_api_whop_orphan_cleanup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whop Cookie Status */
        get: operations["whop_cookie_status_api_whop_cookie_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenarios */
        get: operations["get_scenarios_api_sim_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim/run/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Run Scenario */
        post: operations["post_run_scenario_api_sim_run__name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BrokerStatusOut
         * @description Snapshot of the running broker — whether it's a live LongPortClient
         *     or fell back to NoopBrokerClient, plus the last init error if any.
         */
        BrokerStatusOut: {
            /** Is Real */
            is_real: boolean;
            /**
             * Account Label
             * @default
             */
            account_label: string;
            /** Dry Run */
            dry_run: boolean;
            /** Last Init Error */
            last_init_error?: string | null;
        };
        /** CancelOk */
        CancelOk: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** CandlestickOut */
        CandlestickOut: {
            /** Timestamp */
            timestamp: string | null;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
            /** Turnover */
            turnover: number;
        };
        /** CandlesticksOut */
        CandlesticksOut: {
            /** Symbol */
            symbol: string;
            /** Period */
            period: string;
            /** Bars */
            bars: components["schemas"]["CandlestickOut"][];
        };
        /**
         * ExecutionOut
         * @description One broker-side ORDER (with partial fills aggregated). The unit
         *     of做T binding + day-PL accounting.
         *
         *     ``order_id`` is the unique key. ``task_id`` (nullable) links back to
         *     the signal-station ``tasks`` row that submitted this order — present
         *     only for orders that went through the trader pipeline; manual fills
         *     placed via the LongBridge app / web have ``task_id = null``.
         */
        ExecutionOut: {
            /** Order Id */
            order_id: string;
            /** Task Id */
            task_id?: string | null;
            /** Symbol */
            symbol: string;
            /** Ticker */
            ticker: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /** Qty */
            qty: number;
            /** Price */
            price: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** ExecutionsOut */
        ExecutionsOut: {
            /** Executions */
            executions: components["schemas"]["ExecutionOut"][];
            /** Last Synced At */
            last_synced_at?: string | null;
            /**
             * Total Count
             * @default 0
             */
            total_count: number;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Whop */
            whop: string;
            /** Longport */
            longport: string;
            /**
             * Account Label
             * @default
             */
            account_label: string;
            /** Dry Run */
            dry_run: boolean;
        };
        /**
         * InstructionOut
         * @description Union serializer for Stock/Option — carries a discriminator field.
         */
        InstructionOut: {
            /**
             * Type
             * @description stock | option
             */
            type: string;
            /** Instruction Type */
            instruction_type: string;
            /** Price */
            price: number | null;
            /** Price Range */
            price_range: [
                number,
                number
            ] | null;
            /** Quantity */
            quantity: number | null;
            /** Position Size */
            position_size: string | null;
            /** Stop Loss Price */
            stop_loss_price: number | null;
            /** Take Profit Price */
            take_profit_price: number | null;
            /** Context Source */
            context_source: string | null;
            /** Parser Notes */
            parser_notes: string[];
            /** Referenced Lot Price */
            referenced_lot_price?: number | null;
            /** Ticker */
            ticker?: string | null;
            /** Symbol */
            symbol?: string | null;
            /** Sell Quantity */
            sell_quantity?: string | null;
            /** Option Type */
            option_type?: string | null;
            /** Strike */
            strike?: number | null;
            /** Expiry */
            expiry?: string | null;
        };
        /** LongPortAccountActivateIn */
        LongPortAccountActivateIn: {
            /** Account Id */
            account_id: string;
        };
        /** LongPortAccountLogoutIn */
        LongPortAccountLogoutIn: {
            /** Account Id */
            account_id: string;
        };
        /**
         * LongPortAccountOut
         * @description One OAuth-authorized LongBridge account slot in the settings list.
         *
         *     ``account_id`` is the registered Longbridge OAuth client_id (stable
         *     per Longbridge account). ``label`` is a user-chosen display name.
         *     ``authorized`` reflects whether the SDK token cache holds a valid
         *     token for that account.
         */
        LongPortAccountOut: {
            /** Account Id */
            account_id: string;
            /** Label */
            label: string;
            /** Authorized */
            authorized: boolean;
        };
        /** LongPortAccountRenameIn */
        LongPortAccountRenameIn: {
            /** Account Id */
            account_id: string;
            /** Label */
            label: string;
        };
        /**
         * LongPortOAuthStartOut
         * @description Returned by POST /oauth/start — the URL is opened in a new tab and
         *     the session_id is polled by /oauth/status until completion. The new
         *     account_id is added to the settings list only after success.
         */
        LongPortOAuthStartOut: {
            /** Session Id */
            session_id: string;
            /** Auth Url */
            auth_url: string;
            /** Account Id */
            account_id: string;
        };
        /** LongPortOAuthStatusOut */
        LongPortOAuthStatusOut: {
            /**
             * State
             * @enum {string}
             */
            state: "awaiting_url" | "ready" | "success" | "error" | "cancelled";
            /** Error */
            error?: string | null;
            /** Account Id */
            account_id?: string | null;
        };
        /** LongPortSettingsOut */
        LongPortSettingsOut: {
            /** Active Account Id */
            active_account_id: string | null;
            /** Accounts */
            accounts: components["schemas"]["LongPortAccountOut"][];
            /** Auto Trade */
            auto_trade: boolean;
            /** Region */
            region: string;
            /** Dry Run */
            dry_run: boolean;
        };
        /**
         * LongPortSettingsPatch
         * @description Mutable subset of LongPort settings. Account list is managed via the
         *     OAuth + account endpoints and cannot be patched here.
         */
        LongPortSettingsPatch: {
            /** Auto Trade */
            auto_trade?: boolean | null;
            /** Region */
            region?: string | null;
            /** Dry Run */
            dry_run?: boolean | null;
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: string;
            /** Content */
            content: string;
            /** Raw Content */
            raw_content: string;
            /** Author */
            author: string | null;
            /** Source */
            source: string;
            /**
             * Posted At
             * Format: date-time
             */
            posted_at: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Url */
            url?: string | null;
            /** Quoted Message Id */
            quoted_message_id: string | null;
        };
        /** OrphanCleanupRequest */
        OrphanCleanupRequest: {
            /** Url */
            url?: string | null;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** OrphanCleanupResponse */
        OrphanCleanupResponse: {
            /** Deleted Count */
            deleted_count: number;
        };
        /** PositionOut */
        PositionOut: {
            /** Symbol */
            symbol: string;
            /** Type */
            type: string;
            /** Ticker */
            ticker: string;
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost: number | null;
            /** Name */
            name?: string | null;
            /** Option Strike */
            option_strike?: number | null;
            /** Option Expiry */
            option_expiry?: string | null;
            /** Option Type */
            option_type?: string | null;
        };
        /** PositionsOut */
        PositionsOut: {
            /** Stocks */
            stocks: components["schemas"]["PositionOut"][];
            /** Options */
            options: components["schemas"]["PositionOut"][];
        };
        /** PushEventOut */
        PushEventOut: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Order Id */
            order_id: string;
            /** State */
            state: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Delta Qty */
            delta_qty: number | null;
            /** Delta Price */
            delta_price: number | null;
            /** Cumulative Qty */
            cumulative_qty: number | null;
            /** Cumulative Avg Price */
            cumulative_avg_price: number | null;
            /** Note */
            note: string | null;
            /** Submitted Price */
            submitted_price?: number | null;
            /** Submitted Quantity */
            submitted_quantity?: number | null;
        };
        /** QuoteOut */
        QuoteOut: {
            /** Symbol */
            symbol: string;
            /** Last Done */
            last_done: number;
            /** Prev Close */
            prev_close: number;
            /** Today Close */
            today_close?: number | null;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Volume */
            volume: number;
            /** Turnover */
            turnover: number;
            /** Change */
            change: number;
            /** Change Pct */
            change_pct: number;
            /**
             * Trade Session
             * @default regular
             * @enum {string}
             */
            trade_session: "regular" | "pre" | "post" | "overnight" | "closed";
        };
        /**
         * QuoteWatchIn
         * @description Request body for ``POST /api/quotes/watch``.
         *
         *     Replaces the active quote-push watch set with ``symbols``. Backend
         *     diffs vs. the prior set and issues subscribe/unsubscribe calls to the
         *     broker. Empty list clears all subscriptions (e.g. on dashboard close).
         */
        QuoteWatchIn: {
            /** Symbols */
            symbols: string[];
        };
        /**
         * QuoteWatchOut
         * @description Response body for ``POST /api/quotes/watch`` — observability fields
         *     so the UI / log can confirm the diff actually took effect.
         */
        QuoteWatchOut: {
            /** Added */
            added: number;
            /** Removed */
            removed: number;
            /** Total */
            total: number;
        };
        /** QuotesOut */
        QuotesOut: {
            /** Quotes */
            quotes: components["schemas"]["QuoteOut"][];
        };
        /** ScenarioOverviewOut */
        ScenarioOverviewOut: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Source */
            source: string;
            /** Message Text */
            message_text: string;
            /** Push Step Count */
            push_step_count: number;
        };
        /** ScenariosOut */
        ScenariosOut: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioOverviewOut"][];
        };
        /** SimRunOut */
        SimRunOut: {
            /** Scenario Name */
            scenario_name: string;
            /** Message Id */
            message_id: string;
            /** Order Id */
            order_id?: string | null;
            /**
             * Started
             * @default true
             */
            started: boolean;
        };
        /** StatsTodayOut */
        StatsTodayOut: {
            /** Msg Count */
            msg_count: number;
            /** Parse Ok */
            parse_ok: number;
            /** Parse Rate */
            parse_rate: number;
            /** Orders */
            orders: number;
            /** Filled */
            filled: number;
            /** Rejected */
            rejected: number;
        };
        /**
         * TPairAllocation
         * @description One trade's allocation into a做T pair. ``qty`` may be less than the
         *     trade's filled quantity — a trade can be split across multiple pairs.
         */
        TPairAllocation: {
            /** Trade Id */
            trade_id: string;
            /** Qty */
            qty: number;
        };
        /**
         * TPairCreate
         * @description Client selection for a new做T pair. The server computes per-trade
         *     qty allocations using FIFO + min(BUY_avail, SELL_avail) and persists
         *     the result; partial / one-sided selections are accepted.
         */
        TPairCreate: {
            /** Ticker */
            ticker: string;
            /** Symbol */
            symbol?: string | null;
            /**
             * Buy Trade Ids
             * @default []
             */
            buy_trade_ids: string[];
            /**
             * Sell Trade Ids
             * @default []
             */
            sell_trade_ids: string[];
        };
        /**
         * TPairExtendIn
         * @description Add more trades to an existing pair. Same allocation rules apply,
         *     with the existing pair contents counted against trade availability.
         */
        TPairExtendIn: {
            /**
             * Buy Trade Ids
             * @default []
             */
            buy_trade_ids: string[];
            /**
             * Sell Trade Ids
             * @default []
             */
            sell_trade_ids: string[];
        };
        /** TPairOut */
        TPairOut: {
            /** Id */
            id: string;
            /** Ticker */
            ticker: string;
            /** Symbol */
            symbol?: string | null;
            /** Buys */
            buys: components["schemas"]["TPairAllocation"][];
            /** Sells */
            sells: components["schemas"]["TPairAllocation"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TPairsOut */
        TPairsOut: {
            /** Pairs */
            pairs: components["schemas"]["TPairOut"][];
            /**
             * Total Count
             * @default 0
             */
            total_count: number;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
        };
        /** TaskCountOut */
        TaskCountOut: {
            /** Total Count */
            total_count: number;
        };
        /** TaskListOut */
        TaskListOut: {
            /** Tasks */
            tasks: components["schemas"]["TaskSummaryOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** TaskOut */
        TaskOut: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Order Id */
            order_id: string | null;
            /** Submit Order Type */
            submit_order_type?: string | null;
            /** Submit Order Context */
            submit_order_context?: string | null;
            /** Submit Quote Last Done */
            submit_quote_last_done?: number | null;
            /** Submit Price */
            submit_price?: number | null;
            /** Stage Timings */
            stage_timings: {
                [key: string]: number;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Reject Reason */
            reject_reason: string | null;
            message: components["schemas"]["MessageOut"];
            instruction: components["schemas"]["InstructionOut"] | null;
            /** Push Events */
            push_events: components["schemas"]["PushEventOut"][];
            /** Last Cum Qty */
            last_cum_qty?: number | null;
            /** Last Cum Avg Price */
            last_cum_avg_price?: number | null;
            /** Last Submitted Price */
            last_submitted_price?: number | null;
            /** Last Submitted Qty */
            last_submitted_qty?: number | null;
        };
        /** TaskSummaryOut */
        TaskSummaryOut: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Order Id */
            order_id: string | null;
            /** Submit Order Type */
            submit_order_type?: string | null;
            /** Submit Order Context */
            submit_order_context?: string | null;
            /** Submit Quote Last Done */
            submit_quote_last_done?: number | null;
            /** Submit Price */
            submit_price?: number | null;
            /** Stage Timings */
            stage_timings: {
                [key: string]: number;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Reject Reason */
            reject_reason: string | null;
            message: components["schemas"]["MessageOut"];
            instruction: components["schemas"]["InstructionOut"] | null;
            /** Last Cum Qty */
            last_cum_qty?: number | null;
            /** Last Cum Avg Price */
            last_cum_avg_price?: number | null;
            /** Last Submitted Price */
            last_submitted_price?: number | null;
            /** Last Submitted Qty */
            last_submitted_qty?: number | null;
        };
        /** TickerConfigOut */
        TickerConfigOut: {
            /** Trade Quantity */
            trade_quantity: number;
        };
        /**
         * TradeOut
         * @description A single fully-executed (or partial) trade, suitable as a做T
         *     pair member. ``id`` matches the originating task id.
         */
        TradeOut: {
            /** Id */
            id: string;
            /** Ticker */
            ticker: string;
            /** Symbol */
            symbol?: string | null;
            /** Side */
            side: string;
            /** Qty */
            qty: number;
            /** Price */
            price: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Source */
            source?: string | null;
            /** Tag */
            tag?: string | null;
        };
        /** TradesOut */
        TradesOut: {
            /** Ticker */
            ticker: string;
            /** Trades */
            trades: components["schemas"]["TradeOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhopCookieStatusOut */
        WhopCookieStatusOut: {
            /** Exists */
            exists: boolean;
            /** Path */
            path: string;
            /** Last Modified */
            last_modified?: string | null;
            /** Age Seconds */
            age_seconds?: number | null;
        };
        /** WhopPageCreate */
        WhopPageCreate: {
            /** Url */
            url: string;
            /**
             * Source
             * @enum {string}
             */
            source: "stock" | "option";
            /** Name */
            name?: string | null;
        };
        /** WhopPageOut */
        WhopPageOut: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Name */
            name: string;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            settings: components["schemas"]["WhopPageSettingsOut"];
            /** Running */
            running: boolean;
            /** Started At */
            started_at: string | null;
            /** Last Poll At */
            last_poll_at: string | null;
            /** Messages Published */
            messages_published: number;
            /** Last Error */
            last_error: string | null;
        };
        /** WhopPageSettingsOut */
        WhopPageSettingsOut: {
            /** Dedupe Processed Messages */
            dedupe_processed_messages: boolean;
            /** Price Deviation Tolerance */
            price_deviation_tolerance: number;
            /** Block Historical Messages */
            block_historical_messages: boolean;
            /** Launch Headless */
            launch_headless: boolean;
            /**
             * Parser Version
             * @default v1
             * @enum {string}
             */
            parser_version: "v1" | "v2";
            /** Tickers */
            tickers?: {
                [key: string]: components["schemas"]["TickerConfigOut"];
            } | null;
            /** Option Buy Quantity Enabled */
            option_buy_quantity_enabled?: boolean | null;
            /** Option Buy Quantity */
            option_buy_quantity?: number | null;
            /** Option Total Price Limit Enabled */
            option_total_price_limit_enabled?: boolean | null;
            /** Option Total Price Limit */
            option_total_price_limit?: number | null;
        };
        /**
         * WhopPageSettingsPatch
         * @description Local update; any unspecified field = unchanged.
         */
        WhopPageSettingsPatch: {
            /** Dedupe Processed Messages */
            dedupe_processed_messages?: boolean | null;
            /** Price Deviation Tolerance */
            price_deviation_tolerance?: number | null;
            /** Block Historical Messages */
            block_historical_messages?: boolean | null;
            /** Launch Headless */
            launch_headless?: boolean | null;
            /** Parser Version */
            parser_version?: ("v1" | "v2") | null;
            /** Tickers */
            tickers?: {
                [key: string]: components["schemas"]["TickerConfigOut"];
            } | null;
            /** Option Buy Quantity Enabled */
            option_buy_quantity_enabled?: boolean | null;
            /** Option Buy Quantity */
            option_buy_quantity?: number | null;
            /** Option Total Price Limit Enabled */
            option_total_price_limit_enabled?: boolean | null;
            /** Option Total Price Limit */
            option_total_price_limit?: number | null;
        };
        /** WhopPagesOut */
        WhopPagesOut: {
            /** Pages */
            pages: components["schemas"]["WhopPageOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tasks_endpoint_api_tasks_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: string | null;
                type?: string | null;
                symbol?: string | null;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_tasks_endpoint_api_tasks_count_get: {
        parameters: {
            query?: {
                status?: string | null;
                type?: string | null;
                symbol?: string | null;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_endpoint_api_tasks__task_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_task_endpoint_api_tasks__task_id__cancel_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelOk"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_today_endpoint_api_stats_today_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsTodayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_endpoint_api_positions_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pairs_endpoint_api_pairs_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                offset?: number;
                limit?: number;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TPairsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pair_endpoint_api_pairs_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TPairCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TPairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extend_pair_endpoint_api_pairs__pair_id__extend_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                pair_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TPairExtendIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TPairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pair_endpoint_api_pairs__pair_id__delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                pair_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_endpoint_api_quote_get: {
        parameters: {
            query: {
                /** @description comma-separated symbols */
                symbols: string;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watch_quotes_endpoint_api_quotes_watch_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteWatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteWatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candlesticks_endpoint_api_candlesticks_get: {
        parameters: {
            query: {
                symbol: string;
                /** @description today | 5 | 7 | 15 | 30 | 60 | 90 */
                period?: string;
                /** @description (today only) 2min | 3min | 5min */
                granularity?: string;
                /** @description (today only) regular | all (include pre/post-market) */
                sessions?: string;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandlesticksOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_executions_endpoint_api_broker_executions_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                days?: number;
                offset?: number;
                limit?: number;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    today_executions_endpoint_api_broker_today_executions_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trades_endpoint_api_trades_get: {
        parameters: {
            query: {
                /** @description user-facing ticker, e.g. TSLA */
                ticker: string;
                limit?: number;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_endpoint_api_health_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_longport_settings_api_longport_settings_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongPortSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_longport_settings_api_longport_settings_patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongPortSettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongPortSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_longport_oauth_start_api_longport_oauth_start_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongPortOAuthStartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_longport_oauth_status_api_longport_oauth_status_get: {
        parameters: {
            query: {
                session_id: string;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongPortOAuthStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_longport_oauth_activate_api_longport_oauth_activate_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongPortAccountActivateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongPortSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_longport_oauth_logout_api_longport_oauth_logout_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongPortAccountLogoutIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongPortSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_longport_oauth_account_api_longport_oauth_account_patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongPortAccountRenameIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongPortSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_broker_status_api_longport_broker_status_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_broker_reload_api_longport_broker_reload_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_task_endpoint_api_tasks__task_id__confirm_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_task_endpoint_api_tasks__task_id__skip_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_whop_pages_api_whop_pages_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopPagesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_whop_page_api_whop_pages_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhopPageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_whop_page_api_whop_pages__page_id__delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_whop_page_api_whop_pages__page_id__restart_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_whop_page_endpoint_api_whop_pages__page_id__start_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_whop_page_endpoint_api_whop_pages__page_id__stop_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whop_settings_defaults_api_whop_pages_defaults_get: {
        parameters: {
            query: {
                source: string;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopPageSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_whop_page_settings_api_whop_pages__page_id__settings_patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhopPageSettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_orphan_tasks_api_whop_orphan_cleanup_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrphanCleanupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrphanCleanupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whop_cookie_status_api_whop_cookie_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopCookieStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenarios_api_sim_scenarios_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenariosOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_run_scenario_api_sim_run__name__post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
