/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks Endpoint
         * @description Return a paginated, optionally-filtered list of tasks.
         *
         *     Pagination is cursor-based: pass ``cursor=<ISO-datetime>`` from
         *     ``next_cursor`` in the previous page to advance.  ``next_cursor`` is
         *     ``null`` when no further pages exist.
         */
        get: operations["list_tasks_endpoint_api_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Endpoint
         * @description Return the fully-hydrated Task including all push_events.
         */
        get: operations["get_task_endpoint_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Task Endpoint
         * @description Cancel the brokerage order associated with a task.
         *
         *     Returns 404 if the task doesn't exist, 400 if it has no ``order_id``
         *     (not yet submitted), or 502 if the broker call fails.
         */
        post: operations["cancel_task_endpoint_api_tasks__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats Today Endpoint
         * @description Return today's task counts grouped into summary buckets.
         */
        get: operations["stats_today_endpoint_api_stats_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Positions Endpoint
         * @description Return current positions split into stocks and options.
         *
         *     Sourced from the ``positions`` table (populated by a future broker-sync
         *     job — returns empty lists until that sync runs).
         */
        get: operations["list_positions_endpoint_api_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Endpoint
         * @description Return service liveness + mode status.
         *
         *     ``whop`` is always ``"down"`` until the Phase 6 Whop scraper is wired
         *     into the health probe.  ``longport`` is assumed ``"up"`` because the
         *     broker is injected at startup (real health-check is future work).
         */
        get: operations["health_endpoint_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Whop Pages */
        get: operations["list_whop_pages_api_whop_pages_get"];
        put?: never;
        /** Create Whop Page */
        post: operations["create_whop_page_api_whop_pages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/pages/{page_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Whop Page */
        delete: operations["delete_whop_page_api_whop_pages__page_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/pages/{page_id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart Whop Page */
        post: operations["restart_whop_page_api_whop_pages__page_id__restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/pages/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whop Settings Defaults */
        get: operations["whop_settings_defaults_api_whop_pages_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/pages/{page_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Whop Page Settings */
        patch: operations["patch_whop_page_settings_api_whop_pages__page_id__settings_patch"];
        trace?: never;
    };
    "/api/whop/orphan/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cleanup Orphan Tasks
         * @description Delete all tasks (and linked rows) for a given url.
         *
         *     Defensive: rejects (400) if the url is currently registered to an
         *     active page — caller should remove the page first to prevent the
         *     listener from immediately re-creating tasks for the same url.
         */
        post: operations["cleanup_orphan_tasks_api_whop_orphan_cleanup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whop/cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whop Cookie Status */
        get: operations["whop_cookie_status_api_whop_cookie_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CancelOk */
        CancelOk: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Whop */
            whop: string;
            /** Longport */
            longport: string;
            /** Mode */
            mode: string;
            /** Dry Run */
            dry_run: boolean;
        };
        /**
         * InstructionOut
         * @description Union serializer for Stock/Option — carries a discriminator field.
         */
        InstructionOut: {
            /**
             * Type
             * @description stock | option
             */
            type: string;
            /** Instruction Type */
            instruction_type: string;
            /** Price */
            price: number | null;
            /** Price Range */
            price_range: [
                number,
                number
            ] | null;
            /** Quantity */
            quantity: number | null;
            /** Position Size */
            position_size: string | null;
            /** Stop Loss Price */
            stop_loss_price: number | null;
            /** Take Profit Price */
            take_profit_price: number | null;
            /** Context Source */
            context_source: string | null;
            /** Parser Notes */
            parser_notes: string[];
            /** Ticker */
            ticker?: string | null;
            /** Symbol */
            symbol?: string | null;
            /** Sell Quantity */
            sell_quantity?: string | null;
            /** Option Type */
            option_type?: string | null;
            /** Strike */
            strike?: number | null;
            /** Expiry */
            expiry?: string | null;
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: string;
            /** Content */
            content: string;
            /** Raw Content */
            raw_content: string;
            /** Author */
            author: string | null;
            /** Source */
            source: string;
            /**
             * Posted At
             * Format: date-time
             */
            posted_at: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Url */
            url?: string | null;
            /** Quoted Message Id */
            quoted_message_id: string | null;
        };
        /** OrphanCleanupRequest */
        OrphanCleanupRequest: {
            /** Url */
            url: string;
        };
        /** OrphanCleanupResponse */
        OrphanCleanupResponse: {
            /** Deleted Count */
            deleted_count: number;
        };
        /** PositionOut */
        PositionOut: {
            /** Symbol */
            symbol: string;
            /** Type */
            type: string;
            /** Ticker */
            ticker: string;
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost: number | null;
            /** Option Strike */
            option_strike?: number | null;
            /** Option Expiry */
            option_expiry?: string | null;
            /** Option Type */
            option_type?: string | null;
        };
        /** PositionsOut */
        PositionsOut: {
            /** Stocks */
            stocks: components["schemas"]["PositionOut"][];
            /** Options */
            options: components["schemas"]["PositionOut"][];
        };
        /** PushEventOut */
        PushEventOut: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            /** Order Id */
            order_id: string;
            /** State */
            state: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Delta Qty */
            delta_qty: number | null;
            /** Delta Price */
            delta_price: number | null;
            /** Cumulative Qty */
            cumulative_qty: number | null;
            /** Cumulative Avg Price */
            cumulative_avg_price: number | null;
            /** Note */
            note: string | null;
        };
        /** StatsTodayOut */
        StatsTodayOut: {
            /** Msg Count */
            msg_count: number;
            /** Parse Ok */
            parse_ok: number;
            /** Parse Rate */
            parse_rate: number;
            /** Orders */
            orders: number;
            /** Filled */
            filled: number;
            /** Rejected */
            rejected: number;
        };
        /** TaskListOut */
        TaskListOut: {
            /** Tasks */
            tasks: components["schemas"]["TaskSummaryOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** TaskOut */
        TaskOut: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Order Id */
            order_id: string | null;
            /** Stage Timings */
            stage_timings: {
                [key: string]: number;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Reject Reason */
            reject_reason: string | null;
            message: components["schemas"]["MessageOut"];
            instruction: components["schemas"]["InstructionOut"] | null;
            /** Push Events */
            push_events: components["schemas"]["PushEventOut"][];
        };
        /** TaskSummaryOut */
        TaskSummaryOut: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Order Id */
            order_id: string | null;
            /** Stage Timings */
            stage_timings: {
                [key: string]: number;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Reject Reason */
            reject_reason: string | null;
            message: components["schemas"]["MessageOut"];
            instruction: components["schemas"]["InstructionOut"] | null;
        };
        /** TickerConfigOut */
        TickerConfigOut: {
            /** Trade Quantity */
            trade_quantity: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhopCookieStatusOut */
        WhopCookieStatusOut: {
            /** Exists */
            exists: boolean;
            /** Path */
            path: string;
            /** Last Modified */
            last_modified?: string | null;
            /** Age Seconds */
            age_seconds?: number | null;
        };
        /** WhopPageCreate */
        WhopPageCreate: {
            /** Url */
            url: string;
            /**
             * Source
             * @enum {string}
             */
            source: "stock" | "option";
            /** Name */
            name?: string | null;
        };
        /** WhopPageOut */
        WhopPageOut: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Name */
            name: string;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            settings: components["schemas"]["WhopPageSettingsOut"];
            /** Running */
            running: boolean;
            /** Started At */
            started_at: string | null;
            /** Last Poll At */
            last_poll_at: string | null;
            /** Messages Published */
            messages_published: number;
            /** Last Error */
            last_error: string | null;
        };
        /** WhopPageSettingsOut */
        WhopPageSettingsOut: {
            /** Dedupe Processed Messages */
            dedupe_processed_messages: boolean;
            /** Price Deviation Tolerance */
            price_deviation_tolerance: number;
            /** Tickers */
            tickers?: {
                [key: string]: components["schemas"]["TickerConfigOut"];
            } | null;
        };
        /**
         * WhopPageSettingsPatch
         * @description Local update; any unspecified field = unchanged.
         */
        WhopPageSettingsPatch: {
            /** Dedupe Processed Messages */
            dedupe_processed_messages?: boolean | null;
            /** Price Deviation Tolerance */
            price_deviation_tolerance?: number | null;
            /** Tickers */
            tickers?: {
                [key: string]: components["schemas"]["TickerConfigOut"];
            } | null;
        };
        /** WhopPagesOut */
        WhopPagesOut: {
            /** Pages */
            pages: components["schemas"]["WhopPageOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tasks_endpoint_api_tasks_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: string | null;
                type?: string | null;
                symbol?: string | null;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_endpoint_api_tasks__task_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_task_endpoint_api_tasks__task_id__cancel_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelOk"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_today_endpoint_api_stats_today_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsTodayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_endpoint_api_positions_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_endpoint_api_health_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_whop_pages_api_whop_pages_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopPagesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_whop_page_api_whop_pages_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhopPageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_whop_page_api_whop_pages__page_id__delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_whop_page_api_whop_pages__page_id__restart_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whop_settings_defaults_api_whop_pages_defaults_get: {
        parameters: {
            query: {
                source: string;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopPageSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_whop_page_settings_api_whop_pages__page_id__settings_patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhopPageSettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_orphan_tasks_api_whop_orphan_cleanup_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrphanCleanupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrphanCleanupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whop_cookie_status_api_whop_cookie_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhopCookieStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
