"""initial schema: tasks messages instructions push_events positions

Revision ID: 4d8877dc7b4f
Revises:
Create Date: 2026-04-25 02:15:06.741597

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d8877dc7b4f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "positions",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("avg_cost", sa.Float(), nullable=True),
        sa.Column("option_strike", sa.Float(), nullable=True),
        sa.Column("option_expiry", sa.Date(), nullable=True),
        sa.Column("option_type", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("order_id", sa.String(), nullable=True),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("side", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("reject_reason", sa.String(), nullable=True),
        sa.Column("stage_timings_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tasks_created_at", "tasks", ["created_at"], unique=False, postgresql_using="btree"
    )
    op.create_index("idx_tasks_status", "tasks", ["status"], unique=False)
    op.create_index("idx_tasks_symbol", "tasks", ["symbol"], unique=False)
    op.create_table(
        "instructions",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("instruction_type", sa.String(), nullable=False),
        sa.Column("context_source", sa.String(), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("raw_content", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quoted_message_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "push_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delta_qty", sa.Integer(), nullable=True),
        sa.Column("delta_price", sa.Float(), nullable=True),
        sa.Column("cumulative_qty", sa.Integer(), nullable=True),
        sa.Column("cumulative_avg_price", sa.Float(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_push_task", "push_events", ["task_id", "received_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_push_task", table_name="push_events")
    op.drop_table("push_events")
    op.drop_table("messages")
    op.drop_table("instructions")
    op.drop_index("idx_tasks_symbol", table_name="tasks")
    op.drop_index("idx_tasks_status", table_name="tasks")
    op.drop_index("idx_tasks_created_at", table_name="tasks", postgresql_using="btree")
    op.drop_table("tasks")
    op.drop_table("positions")
    # ### end Alembic commands ###
