"""add_chat_messages

Revision ID: f0fb2079190e
Revises: d5e6f7a8b9c0
Create Date: 2026-05-18 22:56:36.786592

Adds the ``chat_messages`` table used by the chat-monitor pipeline. Rows
are written directly by ``app.whop.chat_writer`` for pages whose
``WhopPageEntry.source == "chat"``; they do not flow through the
task/instruction pipeline. ``quoted_*`` columns are denormalized so a
row renders correctly even if the referenced message is missing.

Two indexes back the read paths:
- ``idx_chat_messages_page_posted`` — per-page timeline queries.
- ``idx_chat_messages_page_author_posted`` — per-author filtering inside
  a page (e.g., monitoring specific signal authors).

Unrelated stale drift detected by ``--autogenerate`` at generation time
(e.g., ``t_pairs`` / ``broker_executions.t_pair_tags``) was trimmed from
this migration — those tables/columns are created by
``Base.metadata.create_all()`` at app start and are out of scope here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0fb2079190e'
down_revision: Union[str, Sequence[str], None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'chat_messages',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('page_id', sa.String(), nullable=False),
        sa.Column('author', sa.String(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('raw_content', sa.String(), nullable=False),
        sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('quoted_message_id', sa.String(), nullable=True),
        sa.Column('quoted_author', sa.String(), nullable=True),
        sa.Column('quoted_content', sa.String(), nullable=True),
        sa.Column('quoted_posted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_chat_messages_page_posted',
        'chat_messages',
        ['page_id', 'posted_at'],
        unique=False,
    )
    op.create_index(
        'idx_chat_messages_page_author_posted',
        'chat_messages',
        ['page_id', 'author', 'posted_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_messages_page_author_posted', table_name='chat_messages')
    op.drop_index('idx_chat_messages_page_posted', table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
